### ISSUE TITLE
Faster RCNN performance metrics

### ISSUE THREAD

**Issue by kalikhademi** [wingedrasengan927/pytorch-tutorials#3]
Hi, 

I have one question about the computation of metrics for the faster RCNN result using your method. I would like to compute if a detection is TP,FP, or FN using the detections made by FASTER RCNN inference function. Is the proposal_final which is the output of inference function, the final bounding box detections that I can compute its IOU with the ground truth bounding boxes?

Thanks,

**Comment by wingedrasengan927** [comment]
Yes. First you've got to project `proposals_final` to the image space using the `project_bboxes` function. Then you can compute IoU of every proposal with the ground truth boxes and calculate TP, FP, FN accordingly. Also, in some cases the proposal may cross the image. So you might want to clip them using the `clip_boxes_to_image` function provided by torch.
check this link for more details: https://pytorch.org/vision/stable/generated/torchvision.ops.clip_boxes_to_image.html
